### ISSUE TITLE
Did you mean to use React.forwardRef()

### ISSUE THREAD

**Issue by rocrinioica** [jakex7/react-native-click-outside#6]
Hi, i get the following error:
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Do you have any idea why i get the error?

**Comment by jakex7** [comment]
Hi @rocrinioica,
The reason for this issue is React's requirement that the ref refers to the actual element, not the component. You can achieve this in two ways: 
1. apply the ref to, for example, View in the component above
```tsx
  const ref = useClickOutside<Text>(() => setIsOpen(false));
  return (
    <ClickOutsideProvider>
      <View ref={ref}>
        <SomeComponent />
      </View>
    </ClickOutsideProvider>
  );
```
2. pass the ref through React.forwardRef and overlay it on the wrapper
```tsx
// root component A
export const DropdownExample = () => {
  // ...
  const ref = useClickOutside(() => setIsOpen(false));
  return (
    <ClickOutsideProvider>
      <SomeComponent ref={ref} />
    </ClickOutsideProvider>
  );
};

// child component B
const SomeComponent = React.forwardRef<View, SomeComponentProps>((p, ref) => {
  return (
    <View ref={ref}>
      {/* ... */}
    </View>
  );
});
```

I hope you find it helpful, if there is anything else, I will be happy to help 😃
