### ISSUE TITLE
Need to set background color to work

### ISSUE THREAD

**Issue by syahirdev** [jakex7/react-native-click-outside#8]
I tried using fresh new Expo + NativeWind project. When I didn't set a background color for an element, the useClickOutside feature didn't work. But when I added a background color like "bg-red-500" or "bg-transparent," it started working. How can I make it work without needing a background color?

e.g. (not working)
```
<View className="flex-1">
      <View ref={ref} className="p-3">
        <Text>test</Text>
      </View>
</View>
```

e.g. (working)
```
<View className="flex-1">
      <View ref={ref} className="p-3 bg-transparent">
        <Text>test</Text>
      </View>
</View>
```

**Comment by jakex7** [comment]
Hi @syahirdev,
Thanks for bringing up this issue. From my tests, it appears that there is such a problem on Android, and it is caused by the fact that Android removes View, which has no significant impact on the appearance. As stated in documentation

> Views that are only used to layout their children or otherwise don't draw anything may be automatically removed from the native hierarchy as an optimization. 
Source: https://reactnative.dev/docs/view#collapsable-android

To solve this problem, I recommend setting prop `collapsable` to `false` for such troublesome elements.

Example:
```jsx
        <View ref={ref} collapsable={false}>
          <Text>TEST</Text>
        </View>
```

I will soon add relevant changes to the documentation. If you have other problems or questions, feel free to reopen/open a new issue
